"""
world.py — functions to create animations
Do not edit this file!
All customization is in the main script.
"""

import pygame
import random
import math

# generate a list of random star positions (called once at startup)
def make_stars(count, width, ground_level):
    return [(random.randint(0, width), random.randint(0, ground_level)) for _ in range(count)]

# draw a color-cycling background
def cycle_sky(screen, sky_tick, sky_red_range, sky_green_range, sky_blue_range, sky_speed):
    sky_tick += sky_speed
    wave = (math.sin(sky_tick * 0.02) + 1) / 2
    r = int(sky_red_range[0]   + wave * (sky_red_range[1]   - sky_red_range[0]))
    g = int(sky_green_range[0] + wave * (sky_green_range[1] - sky_green_range[0]))
    b = int(sky_blue_range[0]  + wave * (sky_blue_range[1]  - sky_blue_range[0]))
    screen.fill((r, g, b))
    return sky_tick

# Draw the background stars
def draw_stars(screen, stars, star_color):
    for star in stars:
        pygame.draw.circle(screen, star_color, star, 2)

# Draw the sun or moon
def draw_sun(screen, show_sun, sun_x, sun_y, sun_size, sun_color):
    if show_sun:
        pygame.draw.circle(screen, sun_color, (sun_x, sun_y), sun_size)

# draw the ground
def draw_ground(screen, ground_color, ground_level, width):
    pygame.draw.rect(screen, ground_color, (0, ground_level + 20, width, 60))

# Draw the sparkle trail
def draw_trail(screen, trail, sparkle_color, trail_size):
    for point in trail:
        if isinstance(sparkle_color[0], tuple):
            # shimmer - roll a fresh color for each dot
            color = (
                random.randint(sparkle_color[0][0], sparkle_color[0][1]),
                random.randint(sparkle_color[1][0], sparkle_color[1][1]),
                random.randint(sparkle_color[2][0], sparkle_color[2][1]),
            )
        else:
            # fixed color
            color = sparkle_color
        pygame.draw.circle(screen, color, point, trail_size)

# Draw the player as an emoji or shape
def draw_player(screen, x, y, use_emoji, emoji_font, player_emoji, player_color, player_size):
    if use_emoji:
        surface = emoji_font.render(player_emoji, True, (255, 255, 255))
        screen.blit(surface, (x - player_size, y - player_size))
    else:
        pygame.draw.circle(screen, player_color, (x, y), player_size)